4 create footer
FrontEdgeIT/frontedge-wp-gatsby pull request #32
Opened 2021-05-21 08:15 UTC by ali-suliman

Before you submit your Pull Request, please fill out this form and make sure you have done all checks:

## 4
*Replace #issue with # + issue number. Ex. #1*

This PR closes #issue

## Changes that effect other group members
Does your solution include things that will affect the working condition of the webpage for the other group members? 

- No

*ex. added dependencies, updated .env files*

Give a brief description of what the other group members need know to make the repo run correctly

- Fixed footer component

- [x] I have notified the other team members of the required changes/updates

## Checks
- [x] I have run `npm run lint`
- [x] I have used the common styles in common.scss

I have checked that the solution works in;

- [x] Chrome
- [x] Edge
- [x] Firefox
- [ ] Safari (only do this check if you are on a mac computer, Windows no longer supports newer versions of Safari)

2021-05-21 08:27 UTC, jensengbg-johanna-jansson commented on src/pages/index.scss
>  a {
Jag har glömt byta namn på burlow, det borde vara barlow. När du ändå gör dina ändringar kan du döpa om alla burlow till barlow

2021-05-21 08:28 UTC, jensengbg-johanna-jansson commented on src/pages/index.scss
>  }
Du kan ta bort denna. Jag la till den bara för att testa att scssen fungerade

2021-05-21 08:57 UTC, jensengbg-johanna-jansson commented on src/components/Footer/Footer.js
> +    <img src={logoFooter} alt="logo " className="footer-logo" />
Lägg bilden sist så den inte blockar alla länkar, och lägg på opacity som i Figma.

2021-05-21 08:59 UTC, jensengbg-johanna-jansson commented on src/components/Footer/Footer.js
> +        <h3>Data Protection</h3>
Heading bordern är inte alignad
![image](https://user-images.githubusercontent.com/54850787/119111698-987eca80-ba23-11eb-83eb-0fa6eb798e67.png)

2021-05-21 09:11 UTC, jensengbg-johanna-jansson requested changes
Ser bra ut!
Har lämnat lite kommentarer på några saker som kan fixas. 
Vad gäller PR templaten så vill jag att ni skriver ert issue nummer på den raden där det står "This PR closes #issue" och byter där ut #issue till sitt eget issue nummer. Så i denna PRen hade du alltså skrivit #4 istället för #issue. Om man inte skriver på detta sett kommer inte ens issue att kopplas korrekt

2021-05-24 06:54 UTC, jensengbg-johanna-jansson commented on pull_request_template.md
> +## 4
Jag vet inte om du gjorde så här, tänkte inte på det första gången jag gick igenom din PR, men du ska inte skriva i denna filen. Den här filen fungerar som en template-fil. Det är en speciell fil som GitHub automatiskt läser in i alla pull requests (i fältet där man kan skriva en beskrivning av sin pull request). Så du skriver i det fältet när du gör din PR.
Så ta bort det du skrivit i filen och uppdatera beskrivningen i din PR istället :)

2021-05-25 04:53 UTC, ali-suliman reviewed
Fixed issues

2021-05-26 06:37 UTC, jensengbg-johanna-jansson commented on src/pages/index.js
> +  // padding: 96,
Ta bort allt som du kommenterar bort

2021-05-26 06:50 UTC, jensengbg-johanna-jansson approved these changes

2021-05-26 06:51 UTC, merged